### ISSUE TITLE
TypedArrayOf removed

### ISSUE THREAD

**Issue by EntityB** [bobcob7/wasm-basic-triangle#2]
https://github.com/bobcob7/wasm-basic-triangle/blob/0092fd00bfb5ff0551d3e8c26bf07f339c657d14/bundle.go#L68

Code can't be compiled with go 1.13, because `TypedArray`  was removed:

https://github.com/golang/go/commit/c468ad04177c422534ad1ed4547295935f84743d

**Comment by justinclift** [comment]
Annoyingly, the replacement for `TypedArrayOf()` (`CopyBytesToGo()`) *only* caters to []byte, rather than all of the other commonly used slice/array types (eg []float32).  Someone will probably need to add some further equivalents for the other slice types, to make things usable.

**Comment by EntityB** [comment]
@justinclift indeed, I have also notice that. 

I have found this solution, it will for sure solve the problem now, but it is not "native": 
https://github.com/hajimehoshi/ebiten/blob/c52e043006dacb6684d4b2ee0dc135cf9f0ddec4/internal/jsutil/go113_js.go

**Comment by justinclift** [comment]
Yeah, @hajimehoshi kindly pointed at that on Slack a few days ago.  I'll try it out in a few days, as I'm not (yet) quite up to having to dive back into WebGL with Go. :grin:

**Comment by bobcob7** [comment]
lol, only took me 3 years to dive back into WebGL.
